require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.autocommands"
require "user.cmp"
require "user.treesitter"
require "user.gitsigns"
require "user.autopairs"
require "user.illuminate"
require "user.nvim-tree"
require "user.colorscheme"
require "user.lsp"
require "user.comment"
require "user.bufferline"
