-- require "user.impatient"
-- require "user.options"
-- require "user.keymaps"
-- require "user.autocommands"

-- require "user.plugins"
-- require "user.autopairs"
-- require "user.comment"
-- require "user.colorscheme"
-- require "user.cmp"
-- require "user.gitsigns"
-- require "user.illuminate"
-- require "user.indentline"
-- require "user.nvim-tree"
-- require "user.bufferline"
-- require "user.lualine"
-- require "user.treesitter"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.lsp"
-- require "user.dap"
-- require "user.alpha"
-- require "user.telescope"

require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocommands"

spec "user.colorscheme"
spec "user.devicons"
spec "user.lualine"
spec "user.nvimtree"
spec "user.scrollbar"
spec "user.toggleterm"

spec "user.mason"
spec "user.lspconfig"
spec "user.none-ls"
spec "user.treesitter"

spec "user.whichkey"
spec "user.telescope"
spec "user.project"

spec "user.comment"
spec "user.illuminate"
spec "user.indentline"
spec "user.cmp"
spec "user.gitsigns"
spec "user.autopairs"

require "user.lazy"
