require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.autocommands"

require "user.plugins"
require "user.autopairs"
require "user.comment"
require "user.colorscheme"
require "user.cmp"
require "user.gitsigns"
require "user.illuminate"
require "user.indentline"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.treesitter"
require "user.toggleterm"
require "user.project"
require "user.lsp"
-- require "user.dap"
-- require "user.alpha"
-- require "user.telescope"
